services:
  - name: "tftesting-service"
    tag_rules:
      - tag_prefix: "." # matches all tagged images
        keep_count: 3
    untagged_expiry_days: 2
  - name: "mtls-sidecar"
    tag_rules:
      - tag_prefix: "." # matches all tagged images
        keep_count: 5
    untagged_expiry_days: 20
