sonar.sources=src
sonar.tests=src/tests
sonar.exclusions=src/tests/**,**/__pycache__/**,**/*.pyc,**/requirements.in
sonar.test.inclusions=src/tests/test_*.py
sonar.python.version=3.13
sonar.python.coverage.reportPaths=src/coverage.xml