sonar.projectKey=cdap-set-log-retention
sonar.projectName=cdap-set-log-retention
sonar.python.version=3.11
sonar.tests=.
sonar.test.inclusions=test_*.py
sonar.python.coverage.reportPaths=coverage.xml
