locals {
  # cdap-test manages dev + test
  # cdap-prod manges sandbox + prod
  managed_envs = var.app == "cdap" ? (
    contains(["dev", "test"], var.env) ? ["dev", "test"] : ["sandbox", "prod"]
  ) : []

  managed_apps = ["ab2d", "bcda", "dpc"]

  #A All app-env environment keys CDAP manages
  cdap_managed_env_key_aliases = var.app == "cdap" ? flatten([
    for app in local.managed_apps : [
      for env in local.managed_envs : "${app}-${env}"
    ]
  ]) : []

  cdap_managed_env_key_aliases_secondary = var.app == "cdap" ? flatten([
    for app in local.managed_apps : [
      for env in local.managed_envs : "${app}-${env}"
    ]
  ]) : []

  # all KMS aliases that were generated by other repositories CDAP will manage
  cdap_managed_kms_aliases = var.app == "cdap" ? flatten([
    for app in local.managed_apps : [
      for env in local.managed_envs : try(
        yamldecode(
          file("${path.module}/config/${app}/${env}.yml")
        ).additional_kms,
        []
      )
    ]
  ]) : []
}

data "aws_kms_alias" "cdap_managed_kms" {
  for_each = toset(local.cdap_managed_kms_aliases)
  name     = "alias/${each.key}"
}

# Primary region all app/env environment keys
data "aws_kms_alias" "cdap_managed_env_keys" {
  for_each = toset(local.cdap_managed_env_key_aliases)
  name     = "alias/${each.key}"
}

# Secondary region all app/env environment keys
data "aws_kms_alias" "cdap_managed_env_keys_secondary" {
  for_each = toset(local.cdap_managed_env_key_aliases_secondary)
  provider = aws.secondary
  name     = "alias/${each.key}"
}

data "aws_iam_policy_document" "github_actions_cdap" {
  # CodeBuild - managed by CDAP terraservice
  statement {
    actions = [
      "codebuild:BatchGetProjects",
      "codebuild:CreateProject",
      "codebuild:CreateWebhook",
      "codebuild:DeleteProject",
      "codebuild:DeleteSourceCredentials",
      "codebuild:DeleteWebhook",
      "codebuild:List*",
      "codebuild:UpdateProject",
      "codebuild:UpdateProjectVisibility",
      "codebuild:UpdateWebhook",
    ]
    resources = ["*"]
  }

  # ECR Read — CDAP needs to describe all apps' repositories
  # for cross-app infrastructure management
  statement {
    sid = "EcrReadAllApps"
    actions = [
      "ecr:BatchCheckLayerAvailability",
      "ecr:BatchGetImage",
      "ecr:Describe*",
      "ecr:GetLifecyclePolicy",
      "ecr:List*",
    ]
    resources = ["*"]
  }


  statement {
    sid = "KmsCreate"
    actions = [
      "kms:CreateKey",
      "kms:CreateAlias",
      "kms:Describe*"
    ]
    resources = ["*"]
  }

  # FIXME CDAP manages all KMS keys so this permission could be broad
  # FIXME Deprecate the bcda key as the account environment key
  statement {
    sid = "KmsKeyAdmin"
    actions = [
      "kms:EnableKeyRotation",
      "kms:PutKeyPolicy",
      "kms:TagResource",
    ]
    resources = length(data.aws_kms_alias.cdap_managed_kms) > 0 ? concat(
      # Additional/adhoc keys from config files
      values(data.aws_kms_alias.cdap_managed_kms)[*].target_key_arn,
      # Per-app, per-env environment keys (e.g. ab2d-test, dpc-dev, etc.)
      values(data.aws_kms_alias.cdap_managed_env_keys)[*].target_key_arn,
      values(data.aws_kms_alias.cdap_managed_env_keys_secondary)[*].target_key_arn,
      # Account-level keys
      [data.aws_kms_alias.environment_key.target_key_arn],
      [data.aws_kms_alias.account_env_old.target_key_arn],
      [data.aws_kms_alias.account_env_old_secondary.target_key_arn],
      [data.aws_kms_alias.account_env.target_key_arn],
      [data.aws_kms_alias.account_env_secondary.target_key_arn],
    ) : ["*"]
  }

  # Secrets Manager - only CDAP uses this
  statement {
    actions = [
      "secretsmanager:CreateSecret",
      "secretsmanager:DeleteResourcePolicy",
      "secretsmanager:DescribeSecret",
      "secretsmanager:GetResourcePolicy",
      "secretsmanager:GetSecretValue",
      "secretsmanager:PutResourcePolicy",
      "secretsmanager:PutSecretValue",
      "secretsmanager:TagResource",
      "secretsmanager:UntagResource",
    ]
    resources = ["*"]
  }
  statement {
    sid = "S3SharedBucketTagging"
    actions = [
      "s3:GetAccelerateConfiguration",
      "s3:GetBucketAcl",
      "s3:GetBucketCORS",
      "s3:GetBucketLocation",
      "s3:GetBucketLogging",
      "s3:GetBucketNotification",
      "s3:GetBucketOwnershipControls",
      "s3:GetBucketPolicy",
      "s3:GetBucketRequestPayment",
      "s3:GetBucketTagging",
      "s3:GetBucketVersioning",
      "s3:GetBucketWebsite",
      "s3:GetEncryptionConfiguration",
      "s3:GetLifecycleConfiguration",
      "s3:GetBucketObjectLockConfiguration",
      "s3:GetReplicationConfiguration",
      "s3:ListBucket",
      "s3:ListBucketVersions",
      "s3:ListBucketMultipartUploads",
      "s3:CreateBucket",
      "s3:DeleteBucket",
      "s3:DeleteBucketPolicy",
      "s3:PutBucketLogging",
      "s3:PutBucketNotification",
      "s3:PutBucketOwnershipControls",
      "s3:PutBucketPolicy",
      "s3:PutBucketTagging",
      "s3:PutBucketVersioning",
      "s3:PutEncryptionConfiguration",
      "s3:PutLifecycleConfiguration",
    ]
    resources = [
      "arn:aws:s3:::bucket-access-logs-*",
      "arn:aws:s3:::bb2-prod-quicksight-export-*"
    ]
    # FIXME: Add GetBucketObjectLockConfiguration when CDAP adds
    #        log retention / object lock management via Tofu
  }
  # CDAP creates and manages all hosted zones including specialty ones
  # e.g. snowflakecomputing.com via PrivateLink
  # Other teams should not be creating hosted zones directly
  statement {
    sid = "Route53ZoneAdmin"
    actions = [
      "route53:CreateHostedZone",
      "route53:DeleteHostedZone",
      "route53:UpdateHostedZoneComment",
      "route53:AssociateVPCWithHostedZone",
      "route53:DisassociateVPCFromHostedZone",
    ]
    resources = ["*"]
  }

  # Add other CDAP-only services here as needed...
}

resource "aws_iam_policy" "github_actions_cdap" {
  count  = var.app == "cdap" ? 1 : 0
  name   = "${var.app}-${var.env}-github-actions-cdap"
  path   = "/delegatedadmin/developer/"
  policy = data.aws_iam_policy_document.github_actions_cdap.json
}
