name: code-checks (alarm-to-slack-checks)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '../../terraform/services/201-alarm-to-slack/lambda_src/*.py'
      - '../../terraform/services/201-alarm-to-slack/lambda_src/requirements.txt'
      - '.github/workflows/alarm-to-slack-checks.yml'
      - '.github/workflows/checks-reusable.yml'

jobs:
  checks:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/checks-reusable.yml
    secrets: inherit
    with:
      source_path: terraform/services/alarm-to-slack
      sonar_project_key: cdap-alarm-to-slack
