name: code-checks (set-log-retention-checks / cloudwatch log retention)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'scripts/set-log-retention/*.py'
      - 'scripts/set-log-retention/requirements.txt'
      - '.github/workflows/set-log-retention-checks.yml'
      - '.github/workflows/checks-reusable.yml'

jobs:
  checks:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/checks-reusable.yml
    secrets: inherit
    with:
      source_path: scripts/set-log-retention
      sonar_project_key: cdap-set-log-retention
